### Ansible playbook for provision of vms for Lab use
---
- hosts: all
  become: true
  tasks:
          - name: Install packages
            apt:
                  upgrade: yes
                  update_cache: yes
          - name: Install packages
            apt:
                  name: "{{ packages }}"
                  state: latest
                  #update_cache: yes

          - name: load configs
            git:
                    repo: https://github.com/XelK/lab_configs.git
                    dest: "{{remote_git}}"
                    #force: yes
          - name: Config package1
            file:
                    src: "{{remote_git}}/config/tmux.conf"
                    dest: /root/.tmux.conf
                    state: link
          - name: Config package2
            file:
                    src:  "{{remote_git}}/config/nvim"
                    dest: /root/.config/nvim
                    state: link
                    force: yes
          - name: Config package3
            file:
                    src:  "{{remote_git}}/config/bashrc"
                    dest: /root/.bashrc
                    state: link
                    force: yes
          - name: Config package4
            file:
                    src:  "{{remote_git}}/config/bash_aliases"
                    dest: /root/.config/bash_aliases
                    state: link
                    force: yes

  vars:
          packages:
                  - aptitude
                  - tmux
                  - neovim
                    #                  - fzf
          remote_git: "/root/.repo_config"

