# If not running interactively ... get out of here! 

[ -z "$PS1" ] && return

stty -ixon

source /usr/share/fzf/completion.bash
source /usr/share/fzf/key-bindings.bash
export FZF_DEFAULT_OPTS="--preview '(highlight -O ansi -l {} 2> /dev/null ||
cat {} || tree -C {}) 2> /dev/null | head -200'"
complete -o bashdefault -o default -F _fzf_path_completion zathura

	
if pidof tmux 1>/dev/null; then
    eval $(keychain --eval --quiet ~/.ssh/pems/neen/id_rsa);
fi;


export TERM=screen-256color


PATH=$PATH:/usr/local/bin:~/src
#PATH=$PATH:/usr/local/bin:~/src:/snap/bin
# Enable programmable completion features.
if [ -f /usr/share/bash-completion/bash_completion ]; then
    source /usr/share/bash-completion/bash_completion
fi

export EDITOR=nvim
#export VISUAL=code
#export BROWSER=chromium
export BROWSER=firefox

complete -cf sudo

shopt -s autocd #change directory

#history, with arrow, shorter
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
export HISTCONTROL=ignoredups:erasedups
#HISTCONTROL=ignoredups:ignorespace # don't put duplicate lines in the history and force ignoredups and ignorespace
shopt -s histappend  # append to the history file, don't overwrite it
# for setting history length see HISTSIZE and HISTFILESIZE in bash
#HISTSIZE=1000
#HISTFILESIZE=2000
HISTSIZE= HISTFILESIZE= #infinite
export HISTTIMEFORMAT="%d/%m/%y %T "
PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND" # Append commands to the history every time a prompt is shown, instead of after closing the session.

# check the window size after each command and, if necessary,update the values of LINES and COLUMNS.
shopt -s checkwinsize

force_color_prompt=yes # should be on the output of commands, not on the prompt

# Add bash aliases.
if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi

export PS1="\[\033[38;5;1m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\[$(tput sgr0)\]\[\033[38;5;6m\]\H\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]\[\033[38;5;11m\]\w\[$(tput sgr0)\]\[\033[38;5;15m\] \t\n>\[$(tput sgr0)\]"
##### git promt to bash shell ####
GIT_PROMPT_ONLY_IN_REPO=1
source ~/.bash-git-prompt/gitprompt.sh

#export PYTHONPATH=$PYTHONPATH:/usr/lib/python3.6
#export PATH="/usr/local/bin:$PATH"
#export PYTHONPATH="/usr/lib/python2.7/"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
